#!/usr/bin/env python3
import argparse
import time
import os
from typing import Literal



arg_parser = argparse.ArgumentParser(
    prog="P.H.A.A.S.T",
    description="A heuristic-algorithm-driven software made for global minima search",
    epilog="Thanks for choosing Phaast",
    formatter_class = argparse.RawTextHelpFormatter,
)

arg_parser.add_argument(
    "stoichiometry",
    help = "The structure composition (example = C6H6)",
)

arg_parser.add_argument(
    "output_prefix",
    help = "Prefix of the output files (a prefix of \"OUTPUT\" will result in files named OUTPUT0, OUTPUT1, ...)",
)

arg_parser.add_argument(
    "--return_number",
    type = int,
    default = 10,
    help = "Number of least energy molecules to return at the end of the algorithm (default = %(default)s)",
)

arg_parser.add_argument(
    "-pop",
    "--population_size",
    type = int,
    default = 10000,
    help = "Number of molecules in the population (default = %(default)s)",
)

arg_parser.add_argument(
    "-c",
    "--charge",
    type = int,
    default = 0,
    help = "Structure's charge (default = %(default)s)",
)

arg_parser.add_argument(
    "-t", "--threads",
    type = int,
    default = 0,
    help = "Number of threads to be used by the algorithm (default = number of threads on cpu)",
)

arg_parser.add_argument(
    "-xtbt", "--xtb-threads",
    type = int,
    default = 1,
    help = "Number of threads to be used by each -t xtb instance (default = %(default)s)",
)

arg_parser.add_argument(
    "--xtb_path",
    type = str,
    default = "xtb",
    help = "Path to be used for the xtb binary (default = %(default)s)",
)

arg_parser.add_argument(
    "-et",
    "--energy_threshold",
    type = float,
    default = 1e-3,
    help = "Maximum energy difference [in hartree] so molecules are considered alike (default = %(default)s)",
)

arg_parser.add_argument(
    "-gt",
    "--geometry_threshold",
    type = float,
    default = 0.9,
    help = "Maximum geometry difference so molecules are considered the same so one of them is discarded [must be a value between 0 and 1] (default = %(default)s)",
)

arg_parser.add_argument(
    "-gcmp",
    "--generation_children_mutant_proportion",
    nargs = 3,
    type = float,
    default = [1, 1, 1],
    help = "Proportion between new molecules, children and mutants created every new generation (default = 1 1 1)",
)

arg_parser.add_argument(
    "-mdpp",
    "--mutation_displacement_permutation_proportion",
    nargs = 2,
    type = float,
    default = [1, 1],
    help = "Proportion in mutation between atomic displacement and atomic permutation (default = 1 1)",
)

arg_parser.add_argument(
    "-mdm",
    "--mutation_displacement_maximum",
    type = float,
    default = 1,
    help = "Maximum distance (Å) to be used in mutation of atomic displacement (default = %(default)s)",
)

arg_parser.add_argument(
    "-mdn",
    "--mutation_displacement_number",
    type = int,
    default = 1,
    help = "Number of atoms to move in mutations of atomic displacement (default = %(default)s)",
)

arg_parser.add_argument(
    "-mpn",
    "--mutation_permutation_number",
    type = int,
    default = 0,
    help = "Number of permutations in mutations of that type (default = half the number of atoms",
)

arg_parser.add_argument(
    "-loops",
    "--end_loop_number",
    default = 11,
    type = int,
    help = "Number of loops the algorithm will run with the least energy molecule until a new one is found, terminating it (default = %(default)s)",
)

arg_parser.add_argument(
    "--comparison_algorithm",
    default = "mixed",
    type = str,
    help = """Algorithm to be used for structures comparison, the recomendes usage is:
\t- \"grigoryan_springborn\" for clusters;
\t- \"haas_oliveira\" for organic and general shaped structures (check --comparison_bonding_tolerance too);
\t- \"mixed\" for both at the same time (sqrt(grigoryan_springborg * haas_oliveira);
(default = %(default)s)""",
)

arg_parser.add_argument(
    "--comparison_bonding_tolerance",
    default = 0.25,
    type = float,
    help = "Distance tolerable so two atoms can be considered bonded within the haas_oliveira molecule comparison algorithm",
)

arg_parser.add_argument(
    "-v",
    "--verbose",
    action="store_true",
)

args = arg_parser.parse_args()
print(f"Args: {args}")

actual_cwd = os.getcwd()
os.chdir(
    "/".join(__file__.split("/")[:-1])
)

from calculators.xtb import XTB
from computer import Computer
from structure import Base, Molecule
import structure.creator
from structure.creator.filter_list import FilterList, FilterMode
from surface_explorator.genetic import Genetic
from structure.geometry import grigoryan_springborn, haas_oliveira

base = Base(args.stoichiometry)

calc = XTB(
    charge = args.charge,
    threads = args.xtb_threads,
    xtb_path = args.xtb_path,
)

computer = Computer(
    cpu_count_limit = args.threads,
)

computer.add_calculator("xtb", calc)

seed = 2345678

start = time.monotonic_ns()

filter_list = FilterList(FilterMode.EXCLUDE, ((1,1),))

structure_generator = lambda base, n, comp : structure.creator.generate_random_structures_hedron(base, n, comp, 20, filter_list = filter_list)

def haas_oliveira_comparator(mol1 : Molecule, mol2 : Molecule) -> float:
    return haas_oliveira(mol1, mol2, bonding_tolerance = args.comparison_bonding_tolerance)

def mixed_comparator(mol1 : Molecule, mol2 : Molecule) -> float:
    return (haas_oliveira_comparator(mol1, mol2) * grigoryan_springborn(mol1, mol2))**.5


match args.comparison_algorithm:
    case "haas_oliveira":
        comparison_algorithm = haas_oliveira_comparator
    case "grigoryan_springborn":
        comparison_algorithm = grigoryan_springborn
    case "mixed":
        comparison_algorithm = mixed_comparator
    case _:
        raise ValueError(
            f"Incompatible comparison_algorithm: {args.comparison_algorithm}"
        )
        

genetic = Genetic(
    base = base,
    population_size = args.population_size,
    computer = computer,
    calculator = "xtb",

    energy_threshold = args.energy_threshold,

    geometry_threshold = args.geometry_threshold,
    comparison_algorithm = comparison_algorithm,

    generation_children_mutant_proportion = tuple(args.generation_children_mutant_proportion),
    mut_displacement_permutation_proportion = tuple(args.mutation_displacement_permutation_proportion),

    mut_displacement_number = args.mutation_displacement_number,
    mut_displacement_max = args.mutation_displacement_maximum,
    mut_permutation_num = args.mutation_permutation_number,

    end_loop_number = args.end_loop_number,
)

while genetic.loop():
    print(f"========================================")
    print(f"Generation {genetic.cycle_counter} done")
    print(f"Best energy is {genetic.best_energy}")
    print(f"========================================")

end = time.monotonic_ns()
delta_time = (end - start)/1e9

best = sorted(
    genetic.population,
    key = lambda mol: mol.energy,
)

best_list = best[0 : min(len(best), args.return_number)]

print(f"The process is done. Elapsed time: {round(delta_time)} s")
print(f"Total optimizations: {genetic.total_optimizations}")
print(f"Total converged: {genetic.total_converged}")

os.chdir(actual_cwd)

for i, mol in enumerate(best_list):
    mol.to_xyz(f"{args.output_prefix}{i}.xyz")
