#!/bin/bash


binaries=("wget" "tar")

for binary in "${binaries[@]}"; do
    if ! command -v "$binary" &> /dev/null; then

        echo "$binary is not installed"

        exit 1

    fi
done

wget https://github.com/grimme-lab/xtb/releases/download/v6.7.1/xtb-6.7.1-linux-x86_64.tar.xz
tar -xf xtb-6.7.1-linux-x86_64.tar.xz
rm xtb-6.7.1-linux-x86_64.tar.xz

ln -s ./xtb-dist/bin/xtb xtb
