[project]
name = "phaast"
version = "0.0.1"
authors = [
  { name="Daniel Haas", email="danielhaas.ufrj@gmail.com" },
  { name="Ricardo R. Oliveira", email="rrodrigues.iq@gmail.com" },
]
description = """
A modular framework for global minimum search based on heuristic algorithm optimized for multiple processors
"""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE*",]

[project.urls]
Homepage = "https://github.com/D-Haas/phaast"
Issues = "https://github.com/D-Haas/phaast/issues"

[build-system]
requires = [
  "setuptools>=74.1.0",
  "cython"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
ext-modules = [
  {name = "phaast.vec.__init__", sources = ["src/phaast/vec/__init__.pyx"]}
]
