from phaast.structure import Molecule

def energy_difference(mol1 : Molecule, mol2 : Molecule, tolerance : float) -> bool: ...

def grigoryan_springborg(mol1 : Molecule, mol2 : Molecule, tolerance : float) -> bool: ...

def bonding_length(mol1 : Molecule, mol2 : Molecule, tolerance : float, bonding_tolerance : float) -> bool: ...

def charge_difference(mol1 : Molecule, mol2 : Molecule, tolerance : float) -> bool: ...
